# Generated by Django 5.2.17 on 2026-08-07 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(default='%', max_length=10)),
                ('weight', models.FloatField(default=1)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_retired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpis', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='kpi.kpidomain')),
            ],
            options={
                'ordering': ['domain__name', 'group__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_min', models.FloatField(default=100)),
                ('orange_min', models.FloatField(default=80)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('kpi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='kpi.kpi')),
            ],
        ),
        migrations.CreateModel(
            name='KPIGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='kpi.kpidomain')),
            ],
            options={
                'ordering': ['domain__name', 'name'],
                'unique_together': {('domain', 'name')},
            },
        ),
        migrations.AddField(
            model_name='kpi',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='kpi.kpigroup'),
        ),
        migrations.CreateModel(
            name='KPIPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='kpi.kpi')),
                ('periods', models.ManyToManyField(related_name='plans', to='kpi.period')),
                ('regions', models.ManyToManyField(related_name='plans', to='kpi.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='kpi',
            unique_together={('domain', 'group', 'name')},
        ),
        migrations.CreateModel(
            name='KPIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realisation', models.FloatField(default=0)),
                ('objectif', models.FloatField(default=100)),
                ('comment', models.TextField(blank=True, default='')),
                ('validation', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='kpi.kpi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_results', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='kpi.period')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='kpi.region')),
            ],
            options={
                'unique_together': {('kpi', 'period', 'region')},
            },
        ),
        migrations.CreateModel(
            name='ScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_score', models.FloatField()),
                ('commercial_score', models.FloatField(blank=True, null=True)),
                ('technique_score', models.FloatField(blank=True, null=True)),
                ('strategique_score', models.FloatField(blank=True, null=True)),
                ('financier_score', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='kpi.period')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='kpi.region')),
            ],
            options={
                'unique_together': {('period', 'region')},
            },
        ),
    ]
